@file:Suppress("ktlint:standard:no-wildcard-imports")

package com.dessalines.thumbkey.keyboards

import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.*
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontStyle
import androidx.compose.ui.text.font.FontWeight
import com.dessalines.thumbkey.R
import com.dessalines.thumbkey.utils.*
import com.dessalines.thumbkey.utils.ColorVariant.*
import com.dessalines.thumbkey.utils.KeyAction.*


val banfont = FontFamily(Font(R.font.banfont, weight = FontWeight.Normal, style = FontStyle.Normal))

val banmap =
    mapOf(
        "a" to "󱤀",
        "akesi" to "󱤁",
        "ala" to "󱤂",
        "alasa" to "󱤃",
        "ale" to "󱤄",
        "anpa" to "󱤅",
        "ante" to "󱤆",
        "anu" to "󱤇",
        "awen" to "󱤈",
        "e" to "󱤉",
        "en" to "󱤊",
        "esun" to "󱤋",
        "ijo" to "󱤌",
        "ike" to "󱤍",
        "ilo" to "󱤎",
        "insa" to "󱤏",
        "jaki" to "󱤐",
        "jan" to "󱤑",
        "jelo" to "󱤒",
        "jo" to "󱤓",
        "kala" to "󱤔",
        "kalama" to "󱤕",
        "kama" to "󱤖",
        "kasi" to "󱤗",
        "ken" to "󱤘",
        "kepeken" to "󱤙",
        "kili" to "󱤚",
        "kiwen" to "󱤛",
        "ko" to "󱤜",
        "kon" to "󱤝",
        "kule" to "󱤞",
        "kulupu" to "󱤟",
        "kute" to "󱤠",
        "la" to "󱤡",
        "lape" to "󱤢",
        "laso" to "󱤣",
        "lawa" to "󱤤",
        "len" to "󱤥",
        "lete" to "󱤦",
        "li" to "󱤧",
        "lili" to "󱤨",
        "linja" to "󱤩",
        "lipu" to "󱤪",
        "loje" to "󱤫",
        "lon" to "󱤬",
        "luka" to "󱤭",
        "lukin" to "󱤮",
        "lupa" to "󱤯",
        "ma" to "󱤰",
        "mama" to "󱤱",
        "mani" to "󱤲",
        "meli" to "󱤳",
        "mi" to "󱤴",
        "mije" to "󱤵",
        "moku" to "󱤶",
        "moli" to "󱤷",
        "monsi" to "󱤸",
        "mu" to "󱤹",
        "mun" to "󱤺",
        "musi" to "󱤻",
        "mute" to "󱤼",
        "nanpa" to "󱤽",
        "nasa" to "󱤾",
        "nasin" to "󱤿",
        "nena" to "󱥀",
        "ni" to "󱥁",
        "nimi" to "󱥂",
        "noka" to "󱥃",
        "o" to "󱥄",
        "olin" to "󱥅",
        "ona" to "󱥆",
        "open" to "󱥇",
        "pakala" to "󱥈",
        "pali" to "󱥉",
        "palisa" to "󱥊",
        "pan" to "󱥋",
        "pana" to "󱥌",
        "pi" to "󱥍",
        "pilin" to "󱥎",
        "pimeja" to "󱥏",
        "pini" to "󱥐",
        "pipi" to "󱥑",
        "poka" to "󱥒",
        "poki" to "󱥓",
        "pona" to "󱥔",
        "pu" to "󱥕",
        "sama" to "󱥖",
        "seli" to "󱥗",
        "selo" to "󱥘",
        "seme" to "󱥙",
        "sewi" to "󱥚",
        "sijelo" to "󱥛",
        "sike" to "󱥜",
        "sin" to "󱥝",
        "sina" to "󱥞",
        "sinpin" to "󱥟",
        "sitelen" to "󱥠",
        "sona" to "󱥡",
        "soweli" to "󱥢",
        "suli" to "󱥣",
        "suno" to "󱥤",
        "supa" to "󱥥",
        "suwi" to "󱥦",
        "tan" to "󱥧",
        "taso" to "󱥨",
        "tawa" to "󱥩",
        "telo" to "󱥪",
        "tenpo" to "󱥫",
        "bani" to "󱥬",
        "tomo" to "󱥭",
        "tu" to "󱥮",
        "unpa" to "󱥯",
        "uta" to "󱥰",
        "utala" to "󱥱",
        "walo" to "󱥲",
        "wan" to "󱥳",
        "waso" to "󱥴",
        "wawa" to "󱥵",
        "weka" to "󱥶",
        "wile" to "󱥷",
        "namako" to "󱥸",
        "kin" to "󱥹",
        "oko" to "󱥺",
        "kipisi" to "󱥻",
        "leko" to "󱥼",
        "monsuta" to "󱥽",
        "tonsi" to "󱥾",
        "jasima" to "󱥿",
        "kijetesantakalu" to "󱦀",
        "soko" to "󱦁",
        "meso" to "󱦂",
        "epiku" to "󱦃",
        "kokosila" to "󱦄",
        "lanpan" to "󱦅",
        "n" to "󱦆",
        "misikeke" to "󱦇",
        "ku" to "󱦈",
        "pake" to "󱦠",
        "apeja" to "󱦡",
        "majuna" to "󱦢",
        "powe" to "󱦣",
    )

val KB_BAN_THUMBKEY_MAIN =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("https://banner-writer.web.app/image/R", displayText = "R"!!, displayFont = banfont),
                    topLeft = KeyC(".png", displayText = "E"!!, displayFont = banfont),
                    top = KeyC("kute ", displayText = banmap["kute"]!!, displayFont = banfont),
                    topRight = KeyC("kute ", displayText = banmap["kute"]!!, displayFont = banfont),
                    right = KeyC("sijelo ", displayText = banmap["sijelo"]!!, displayFont = banfont),
                    bottomRight = KeyC("moli ", displayText = banmap["moli"]!!, displayFont = banfont),
                    bottom = KeyC("pimeja ", displayText = banmap["pimeja"]!!, displayFont = banfont),
                    bottomLeft = KeyC("supa ", displayText = banmap["supa"]!!, displayFont = banfont),
                    left = KeyC("utala ", displayText = banmap["utala"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("sina ", displayText = banmap["sina"]!!, displayFont = banfont),
                    topLeft = KeyC("kalama ", displayText = banmap["kalama"]!!, displayFont = banfont),
                    top = KeyC("lape ", displayText = banmap["lape"]!!, displayFont = banfont),
                    topRight = KeyC("mama ", displayText = banmap["mama"]!!, displayFont = banfont),
                    right = KeyC("mani ", displayText = banmap["mani"]!!, displayFont = banfont),
                    bottomRight = KeyC("poka ", displayText = banmap["poka"]!!, displayFont = banfont),
                    bottom = KeyC("sike ", displayText = banmap["sike"]!!, displayFont = banfont),
                    bottomLeft = KeyC("lipu ", displayText = banmap["lipu"]!!, displayFont = banfont),
                    left = KeyC("en ", displayText = banmap["en"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("0.", displayText = ""!!, displayFont = banfont),
                    topLeft = KeyC("soweli ", displayText = banmap["soweli"]!!, displayFont = banfont),
                    top = KeyC("pakala ", displayText = banmap["pakala"]!!, displayFont = banfont),
                    topRight = KeyC("awen ", displayText = banmap["awen"]!!, displayFont = banfont),
                    right = KeyC("tu ", displayText = banmap["tu"]!!, displayFont = banfont),
                    bottomRight = KeyC("nasa ", displayText = banmap["nasa"]!!, displayFont = banfont),
                    bottom = KeyC("ante ", displayText = banmap["ante"]!!, displayFont = banfont),
                    bottomLeft = KeyC("wan ", displayText = banmap["wan"]!!, displayFont = banfont),
                    left = KeyC("weka ", displayText = banmap["weka"]!!, displayFont = banfont),
                ),
                EMOJI_KEY_ITEM,
            ),
            listOf(
                KeyItemC(
                    center = KeyC("la ", displayText = banmap["la"]!!, displayFont = banfont),
                    topLeft = KeyC("kin ", displayText = banmap["kin"]!!, displayFont = banfont),
                    top = KeyC("sin ", displayText = banmap["sin"]!!, displayFont = banfont),
                    topRight = KeyC("wawa ", displayText = banmap["wawa"]!!, displayFont = banfont),
                    right = KeyC("nasin ", displayText = banmap["nasin"]!!, displayFont = banfont),
                    bottomRight = KeyC("musi ", displayText = banmap["musi"]!!, displayFont = banfont),
                    bottom = KeyC("sitelen ", displayText = banmap["sitelen"]!!, displayFont = banfont),
                    bottomLeft = KeyC("mije ", displayText = banmap["mije"]!!, displayFont = banfont),
                    left = KeyC("sewi ", displayText = banmap["sewi"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("G", displayText = ""!!, displayFont = banfont),
                    topLeft = KeyC("taso ", displayText = banmap["taso"]!!, displayFont = banfont),
                    top = KeyC("p", displayText = ""!!, displayFont = banfont),
                    topRight = KeyC("lawa ", displayText = banmap["lawa"]!!, displayFont = banfont),
                    right = KeyC("o", displayText = ""!!, displayFont = banfont),
                    bottomRight = KeyC("anu ", displayText = banmap["anu"]!!, displayFont = banfont),
                    bottom = KeyC("i", displayText = ""!!, displayFont = banfont),
                    bottomLeft = KeyC("suno ", displayText = banmap["suno"]!!, displayFont = banfont),
                    left = KeyC("m", displayText = ""!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("0", displayText = ""!!, displayFont = banfont),
                    topLeft = KeyC("ijo ", displayText = banmap["ijo"]!!, displayFont = banfont),
                    top = KeyC("sama ", displayText = banmap["sama"]!!, displayFont = banfont),
                    topRight = KeyC("6", displayText = ""!!, displayFont = banfont),
                    right = KeyC("pana ", displayText = banmap["pana"]!!, displayFont = banfont),
                    bottomRight = KeyC("C", displayText = ""!!, displayFont = banfont),
                    bottom = KeyC("ike ", displayText = banmap["ike"]!!, displayFont = banfont),
                    bottomLeft = KeyC("ale ", displayText = banmap["ale"]!!, displayFont = banfont),
                    left = KeyC("ma ", displayText = banmap["ma"]!!, displayFont = banfont),
                ),
                NUMERIC_KEY_ITEM,
            ),
            listOf(
                KeyItemC(
                    center = KeyC("mi ", displayText = banmap["mi"]!!, displayFont = banfont),
                    topLeft = KeyC("pini ", displayText = banmap["pini"]!!, displayFont = banfont),
                    top = KeyC("lili ", displayText = banmap["lili"]!!, displayFont = banfont),
                    topRight = KeyC("pilin ", displayText = banmap["pilin"]!!, displayFont = banfont),
                    right = KeyC("jo ", displayText = banmap["jo"]!!, displayFont = banfont),
                    bottomRight = KeyC("pali ", displayText = banmap["pali"]!!, displayFont = banfont),
                    bottom = KeyC("lukin ", displayText = banmap["lukin"]!!, displayFont = banfont),
                    bottomLeft = KeyC("tan ", displayText = banmap["tan"]!!, displayFont = banfont),
                    left = KeyC("tomo ", displayText = banmap["tomo"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("e ", displayText = banmap["e"]!!, displayFont = banfont),
                    topLeft = KeyC("sona ", displayText = banmap["sona"]!!, displayFont = banfont),
                    top = KeyC("j", displayText = ""!!, displayFont = banfont),
                    topRight = KeyC("o ", displayText = banmap["o"]!!, displayFont = banfont),
                    right = KeyC("n", displayText = ""!!, displayFont = banfont),
                    bottomRight =
                        KeyC(
                            action = ReplaceTrailingWhitespace(", ", 2),
                            display = KeyDisplay.TextDisplay(","),
                            color = MUTED,
                        ),
                    bottom =
                        KeyC(
                            action = ReplaceTrailingWhitespace(". ", 2),
                            display = KeyDisplay.TextDisplay("."),
                            color = MUTED,
                        ),
                    bottomLeft =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropUp),
                            action = ToggleShiftMode(true),
                            swipeReturnAction = ToggleCurrentWordCapitalization(true),
                            color = MUTED,
                        ),
                    left = KeyC("bani ", displayText = banmap["bani"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("li ", displayText = banmap["li"]!!, displayFont = banfont),
                    topLeft = KeyC("seme ", displayText = banmap["seme"]!!, displayFont = banfont),
                    top = KeyC("kama ", displayText = banmap["kama"]!!, displayFont = banfont),
                    topRight = KeyC("pona ", displayText = banmap["pona"]!!, displayFont = banfont),
                    right = KeyC("mute ", displayText = banmap["mute"]!!, displayFont = banfont),
                    bottomRight = KeyC("tenpo ", displayText = banmap["tenpo"]!!, displayFont = banfont),
                    bottom = KeyC("ona ", displayText = banmap["ona"]!!, displayFont = banfont),
                    bottomLeft = KeyC("pi ", displayText = banmap["pi"]!!, displayFont = banfont),
                    left = KeyC("lon ", displayText = banmap["lon"]!!, displayFont = banfont),
                ),
                BACKSPACE_KEY_ITEM,
            ),
            listOf(
                SPACEBAR_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_BAN_THUMBKEY_SHIFTED =
    KeyboardC(
        listOf(
            listOf(
                KeyItemC(
                    center = KeyC("insa ", displayText = banmap["insa"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("nimi ", displayText = banmap["nimi"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("seli ", displayText = banmap["seli"]!!, displayFont = banfont),
                    // Last char added here
                    bottomRight = KeyC("tonsi ", displayText = banmap["tonsi"]!!, displayFont = banfont),
                    bottom = KeyC("soko ", displayText = banmap["soko"]!!, displayFont = banfont),
                    bottomLeft = KeyC("oko ", displayText = banmap["oko"]!!, displayFont = banfont),
                    left = KeyC("namako ", displayText = banmap["namako"]!!, displayFont = banfont),
                ),
                EMOJI_KEY_ITEM,
            ),
            listOf(
                KeyItemC(
                    center = KeyC("kasi ", displayText = banmap["kasi"]!!, displayFont = banfont),
                    topLeft = KeyC("monsuta ", displayText = banmap["monsuta"]!!, displayFont = banfont),
                    top = KeyC("misikeke ", displayText = banmap["misikeke"]!!, displayFont = banfont),
                    topRight = KeyC("meso ", displayText = banmap["meso"]!!, displayFont = banfont),
                    right = KeyC("leko ", displayText = banmap["leko"]!!, displayFont = banfont),
                    bottomRight = KeyC("lanpan ", displayText = banmap["lanpan"]!!, displayFont = banfont),
                    bottom = KeyC("ku ", displayText = banmap["ku"]!!, displayFont = banfont),
                    bottomLeft = KeyC("kokosila ", displayText = banmap["kokosila"]!!, displayFont = banfont),
                    left = KeyC("kipisi ", displayText = banmap["kipisi"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("luka ", displayText = banmap["luka"]!!, displayFont = banfont),
                    topLeft = KeyC("kijetesantakalu ", displayText = banmap["kijetesantakalu"]!!, displayFont = banfont),
                    top = KeyC("jasima ", displayText = banmap["jasima"]!!, displayFont = banfont),
                    topRight = KeyC("epiku ", displayText = banmap["epiku"]!!, displayFont = banfont),
                    right = KeyC("pu ", displayText = banmap["pu"]!!, displayFont = banfont),
                    bottomRight = KeyC("mu ", displayText = banmap["mu"]!!, displayFont = banfont),
                    bottom = KeyC("unpa ", displayText = banmap["unpa"]!!, displayFont = banfont),
                    bottomLeft = KeyC("laso ", displayText = banmap["laso"]!!, displayFont = banfont),
                    left = KeyC("kala ", displayText = banmap["kala"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("kon ", displayText = banmap["kon"]!!, displayFont = banfont),
                    topLeft = KeyC("jelo ", displayText = banmap["jelo"]!!, displayFont = banfont),
                    top = KeyC("alasa ", displayText = banmap["alasa"]!!, displayFont = banfont),
                    topRight = KeyC("palisa ", displayText = banmap["palisa"]!!, displayFont = banfont),
                    right = KeyC("mun ", displayText = banmap["mun"]!!, displayFont = banfont),
                    bottomRight = KeyC("pan ", displayText = banmap["pan"]!!, displayFont = banfont),
                    bottom = KeyC("pipi ", displayText = banmap["pipi"]!!, displayFont = banfont),
                    bottomLeft = KeyC("nena ", displayText = banmap["nena"]!!, displayFont = banfont),
                    left = KeyC("waso ", displayText = banmap["waso"]!!, displayFont = banfont),
                ),
                NUMERIC_KEY_ITEM,
            ),
            listOf(
                KeyItemC(
                    center = KeyC("len ", displayText = banmap["len"]!!, displayFont = banfont),
                    topLeft = KeyC("loje ", displayText = banmap["loje"]!!, displayFont = banfont),
                    top = KeyC("ko ", displayText = banmap["ko"]!!, displayFont = banfont),
                    topRight = KeyC("jaki ", displayText = banmap["jaki"]!!, displayFont = banfont),
                    right = KeyC("kili ", displayText = banmap["kili"]!!, displayFont = banfont),
                    bottomRight = KeyC("walo ", displayText = banmap["walo"]!!, displayFont = banfont),
                    bottom = KeyC("selo ", displayText = banmap["selo"]!!, displayFont = banfont),
                    bottomLeft = KeyC("a ", displayText = banmap["a"]!!, displayFont = banfont),
                    left = KeyC("monsi ", displayText = banmap["monsi"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("olin ", displayText = banmap["olin"]!!, displayFont = banfont),
                    topLeft = KeyC("lupa ", displayText = banmap["lupa"]!!, displayFont = banfont),
                    top = KeyC("kule ", displayText = banmap["kule"]!!, displayFont = banfont),
                    topRight = KeyC("akesi ", displayText = banmap["akesi"]!!, displayFont = banfont),
                    right = KeyC("lete ", displayText = banmap["lete"]!!, displayFont = banfont),
                    bottomRight =
                        KeyC(
                            action = ReplaceTrailingWhitespace(", ", 2),
                            display = KeyDisplay.TextDisplay(","),
                            color = MUTED,
                        ),
                    bottom =
                        KeyC(
                            action = ReplaceTrailingWhitespace(". ", 2),
                            display = KeyDisplay.TextDisplay("."),
                            color = MUTED,
                        ),
                    bottomLeft =
                        KeyC(
                            display = KeyDisplay.IconDisplay(Icons.Outlined.ArrowDropDown),
                            action = ToggleShiftMode(false),
                            swipeReturnAction = ToggleCurrentWordCapitalization(false),
                            color = MUTED,
                        ),
                    left = KeyC("uta ", displayText = banmap["uta"]!!, displayFont = banfont),
                ),
                KeyItemC(
                    center = KeyC("open ", displayText = banmap["open"]!!, displayFont = banfont),
                    topLeft = KeyC("noka ", displayText = banmap["noka"]!!, displayFont = banfont),
                    top = KeyC("linja ", displayText = banmap["linja"]!!, displayFont = banfont),
                    topRight = KeyC("nanpa ", displayText = banmap["nanpa"]!!, displayFont = banfont),
                    right = KeyC("anpa ", displayText = banmap["anpa"]!!, displayFont = banfont),
                    bottomRight = KeyC("kiwen ", displayText = banmap["kiwen"]!!, displayFont = banfont),
                    bottom = KeyC("suwi ", displayText = banmap["suwi"]!!, displayFont = banfont),
                    bottomLeft = KeyC("sinpin ", displayText = banmap["sinpin"]!!, displayFont = banfont),
                    left = KeyC("poki ", displayText = banmap["poki"]!!, displayFont = banfont),
                ),
                BACKSPACE_KEY_ITEM,
            ),
            listOf(
                SPACEBAR_KEY_ITEM,
                RETURN_KEY_ITEM,
            ),
        ),
    )

val KB_BAN_THUMBKEY: KeyboardDefinition =
    KeyboardDefinition(
        title = "banner thumb-key",
        modes =
            KeyboardDefinitionModes(
                main = KB_BAN_THUMBKEY_MAIN,
                shifted = KB_BAN_THUMBKEY_SHIFTED,
                numeric = NUMERIC_KEYBOARD,
            ),
        settings = KeyboardDefinitionSettings(autoShift = false),
    )
